### ISSUE TITLE
Meta Issue for future development.

### ISSUE THREAD

**Issue by bhaskarvk** [rstudio/leaflet#314]
## Leaflet past 1.1

Leaflet 1.1 releases is very near and this page is a mental note of what needs to be done past 1.1.
### Core Package

New Features and Upgrades
- [ ] Upgrade to [Leaflet JS 1.x](http://leafletjs.com/2016/09/27/leaflet-1.0-final.html).
  - Upgrading the JS lib is no big deal.
  - Making sure all plugins are 1.x compatible (including the ones in leaflet.extras) IS a big deal.
  - One option is to have a new package leaflet2
- [ ] Support [sf](https://github.com/edzer/sfr) data

Improvements
- [ ] Integrate Lodash and more functional Javascript.
- [ ] Split big JS and R files to more modular units. (layers.R, methods.JS are way too big right now).
- [ ] Babel-ify plugin glue javascript.
- [ ] Performance improvements for "big data". (Don't know what it means for now)
### [Leaflet.extras](https://github.com/bhaskarvk/leaflet.extras)
- No new plugins should be put in core leaflet package.
- Leaflet.extras will be the new repo for odds-n-end plugins.
- See [leaflet-extras Issue 6](https://github.com/bhaskarvk/leaflet.extras/issues/6) for a list of plugins 
### Add-on packages

These plugins should be independent packages as they are too big and complex.
- [ ] [Esri.Leaflet](https://github.com/Esri/esri-leaflet)
- [ ] [CartoDB](https://github.com/cartodb/cartodb.js)
- [ ] [Mapbox](https://github.com/mapbox/mapbox.js)
- [ ] [Mapbox GL](https://github.com/mapbox/mapbox-gl-leaflet)
- [ ] [PolarMap](https://github.com/GeoSensorWebLab/polarmap.js)
- [ ] [Mapzen-JS](https://mapzen.com/documentation/mapzen-js)
- [ ] [Tangram](https://mapzen.com/documentation/tangram/Javascript-API/)
- [ ] [Mapzen-Hoverboard](https://github.com/mapzen/hoverboard)
- [ ] [NASA GIBS](https://github.com/aparshin/leaflet-GIBS)
- [ ] [DVF](https://github.com/humangeo/leaflet-dvf)

**Comment by tim-salabim** [comment]
Given that I would like to support sf classes sooner than later (as it is now on CRAN) I guess I'll implement proper methods which we can then migrate to leaflet later?

**Comment by bhaskarvk** [comment]
@tim-salabim Indeed! All this is tentative and should not in any way hold you back from adding features to mapview.

**Comment by mdsumner** [comment]
To support sf, the lists of coordinates for polygons (which are equivalent to sf MULTILINESTRING) need an extra level of hierarchy. There's no problem putting sf MULTIPOLYGONs and POLYGONs into leaflet, these are effectively converted to MULTILINESTRING and then the "evenodd" rule sorts out how the rings overlap. But this leaves the ambiguity about which ring-as-hole belongs to which ring-as-island, an ambiguity present in shapefiles, in sp, and in all packages that use lists of polygon rings modelled on sp.  The ambiguity means that round-tripping, i.e. for edits made in the browser to features that then are returned to R, there needs to be a way to identify holes with their parent island. 

It's also a bit incongruous that the coordinates are called "lng" and "lat", given that much spatial data is projected, but that might be a sensible standard to use. 

I recommend one of

1) move to a list of lists model with the extra structure (always MULTI-forms, no need for the POLYGON and LINESTRING really)
2) move to using sf objects

I've been meaning to illustrate this in detail but it seems important to air early rather than later. Mapview currently decomposes to leaflet polygonData lists that are analogous to MULTILINESTRING (sf uses matrices rather than lists of lng and lat). So this issue has implications across a number of projects.  @tim-salabim @edzer

If I'm missing something and it's not important then I'd be keen to hear the explanation. Also I can illustrate this in detail if needed.

**Comment by jcheng5** [comment]
@mdsumner Sorry, are you talking about leaflet or mapview right now?

**Comment by mdsumner** [comment]
This is all about leaflet - the mapview reference is just there because it builds the exact same structures as leaflet currently uses to support sf, decomposing them to the polygonData form.    

Sorry for the confusion, as I said I mean to illustrate this in detail (it's clear to me now in a way it wasn't last month) and I'm happy to do that.
