### ISSUE TITLE
v2.0.4 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#718]
- [x] `system("npm run build")`
- [x] Update NEWS
- [x] Update Version
- [x] `devtools::document()`
- [x] `devtools::install()`
- [x] `source("scripts/docs_update.R")`
- [x] Make sure major shiny examples display properly
  * [x] [Super Zip](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) 
`shiny::runGitHub("rstudio/shiny-examples", subdir = "063-superzip-example")`
  * [x] [Bus Dashboard](https://github.com/rstudio/shiny-examples/tree/master/086-bus-dashboard)
`shiny::runGitHub("rstudio/shiny-examples", subdir = "086-bus-dashboard")`
- [x] double check licenses
- [x] `source("scripts/viztest.R")`
- [x] `devtools::release(check=TRUE)`, (don't actually release in the last step)
- [x] Check on windows
- [x] `source("scripts/rhub.R")`
- [x] `source("scripts/revdepcheck.R")`
- [ ] Merge to master, then execute 
```r
devtools:::upload_cran(".", "../builds/leaflet_2.0.4.tar.gz")
```
- [ ] When accepted on CRAN, tag commit with version, push tag
