### ISSUE TITLE
Release checklist v2.1

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#775]
- [x] Create `rc-v2.1` branch
- [x] `system("npm run build")`
- [x] Update NEWS
- [x] Update Version
- [x] In `DESCRIPTION`, remove `Remotes:` section
- [x] `devtools::document()`
- [x] `devtools::install()`
- [x] `source("scripts/docs_update.R")`
- [x] Make sure major shiny examples display properly
  * [x] [Super Zip](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) 
`shiny::runGitHub("rstudio/shiny-examples", subdir = "063-superzip-example")`
  * [x] [Bus Dashboard](https://github.com/rstudio/shiny-examples/tree/master/086-bus-dashboard)
`shiny::runGitHub("rstudio/shiny-examples", subdir = "086-bus-dashboard")`
- [x] double check licenses
- [x] `source("scripts/viztest.R")`
- [x] `devtools::release(check=TRUE)`, (don't actually release in the last step)
- [x] Check on windows
- [x] `source("scripts/revdepcheck.R")`
- [x] Merge to master, then execute 
```r
devtools:::upload_cran(".", "../builds/leaflet_2.0.5.tar.gz")
```
- [x] When accepted on CRAN, tag commit with version, push tag

**Comment by jcheng5** [comment]
@schloerke I copied this from v2.0.4, does this look right to you?

**Comment by schloerke** [comment]
No need to run rhub script. The latest GHA is fairly accurate. 

The revdep script does not exist anymore. Standard revdep check should work great. 😃 Let me know if you'd like for me to run this.

I believe the rest looks accurate.

**Comment by jcheng5** [comment]
Got this from `R CMD check --as-cran`

```
Found the following (possibly) invalid URLs:
  URL: https://github.com/leaflet-extras/leaflet-providers/blob/main/leaflet-providers.js
    From: man/providers.Rd
    Status: 404
    Message: Not Found
  URL: https://github.com/lvoogdt/Leaflet.awesome-markers (moved to https://github.com/lennardv2/Leaflet.awesome-markers)
    From: man/awesomeIcons.Rd
    Status: 200
    Message: OK
```
