### ISSUE TITLE
Release checklist v2.1.1

### ISSUE THREAD

**Issue by jcheng5** [rstudio/leaflet#789]
- [x] Create `rc-v2.1.1` branch
- [x] `system("npm run build")`
- [x] Update NEWS
- [x] Update Version
- [x] In `DESCRIPTION`, remove `Remotes:` section
- [x] `devtools::document()`
- [x] `devtools::install()`
- [x] `source("scripts/docs_update.R")`
- [x] Make sure major shiny examples display properly
  * [x] [Super Zip](https://github.com/rstudio/shiny-examples/tree/master/063-superzip-example) 
`shiny::runGitHub("rstudio/shiny-examples", subdir = "063-superzip-example")`
  * [x] [Bus Dashboard](https://github.com/rstudio/shiny-examples/tree/master/086-bus-dashboard)
`shiny::runGitHub("rstudio/shiny-examples", subdir = "086-bus-dashboard")`
- [x] double check licenses
- [x] `source("scripts/viztest.R")`. If you get a `find_img_dir` error, ensure webshot/phantomjs are installed with `install.packages("webshot"); webshot::install_phantomjs()`
- [x] `devtools::release(check=TRUE)`, (don't actually release in the last step)
- [x] Check on windows
- [x] `source("scripts/revdepcheck.R")`
- [x] Merge to master, then execute 
```r
devtools:::upload_cran(".", "../builds/leaflet_2.1.1.tar.gz")
```
- [x] When accepted on CRAN, tag commit with version, push tag
